# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: WinsiderSS.SystemInformer.Canary
PackageVersion: 3.2.25129.1713
InstallerType: exe
Scope: machine
InstallModes:
- silent
- silentWithProgress
- interactive
InstallerSwitches:
  Silent: -install -silent
  SilentWithProgress: -install -silent
  Interactive: -install
  Upgrade: -update -silent
ProductCode: SystemInformer-Canary
ElevationRequirement: elevatesSelf
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/winsiderss/si-builds/releases/download/3.2.25129.1713/systeminformer-3.2.25129.1713-canary-setup.exe
  InstallerSha256: 957282E291E60EA8C70C364005ED10827CAF5057B0E37477FE5D5FF0A4ACA779
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-05-09
