# Created using wingetcreate 1.9.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: WinsiderSS.SystemInformer.Canary
PackageVersion: 3.1.24360.0
InstallerType: exe
Scope: machine
InstallModes:
- silent
- silentWithProgress
- interactive
InstallerSwitches:
  Silent: -install -silent
  SilentWithProgress: -install -silent
  Interactive: -install
  Upgrade: -update -silent
ProductCode: SystemInformer-Canary
ElevationRequirement: elevatesSelf
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/winsiderss/si-builds/releases/download/3.1.24360/systeminformer-3.1.24360-canary-setup.exe
  InstallerSha256: 5DDC06676A25D216E6D445F1E03A1E30F350A6D6C9B053FAB5B0446EBEB4F3D2
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2024-12-25
