# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: WinsiderSS.SystemInformer.Canary
PackageVersion: 3.2.25130.426
InstallerType: exe
Scope: machine
InstallModes:
- silent
- silentWithProgress
- interactive
InstallerSwitches:
  Silent: -install -silent
  SilentWithProgress: -install -silent
  Interactive: -install
  Upgrade: -update -silent
ProductCode: SystemInformer-Canary
ElevationRequirement: elevatesSelf
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/winsiderss/si-builds/releases/download/3.2.25130.426/systeminformer-3.2.25130.426-canary-setup.exe
  InstallerSha256: 785FA81759C860D66E0254C7B87DA224B4DEE7D50F195FE11EE49CC105592D08
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-05-10
