# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: WinsiderSS.SystemInformer.Canary
PackageVersion: 3.2.25128.447
InstallerType: exe
Scope: machine
InstallModes:
- silent
- silentWithProgress
- interactive
InstallerSwitches:
  Silent: -install -silent
  SilentWithProgress: -install -silent
  Interactive: -install
  Upgrade: -update -silent
ProductCode: SystemInformer-Canary
ElevationRequirement: elevatesSelf
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/winsiderss/si-builds/releases/download/3.2.25128.447/systeminformer-3.2.25128.447-canary-setup.exe
  InstallerSha256: 4301C712D8716F21F936ED6F47423729F6DA48CD2EE26DE40714F157CE4F6A3A
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-05-08
