# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: WinsiderSS.SystemInformer.Canary
PackageVersion: 3.2.25044.407
InstallerType: exe
Scope: machine
InstallModes:
- silent
- silentWithProgress
- interactive
InstallerSwitches:
  Silent: -install -silent
  SilentWithProgress: -install -silent
  Interactive: -install
  Upgrade: -update -silent
ProductCode: SystemInformer-Canary
ElevationRequirement: elevatesSelf
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/winsiderss/si-builds/releases/download/3.2.25044.407/systeminformer-3.2.25044.407-canary-setup.exe
  InstallerSha256: BE5DFB7D7994A04912DA7A4368A226850D8B4D2A30CB34795FFF0A0130343F6B
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-02-13
