# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: WinsiderSS.SystemInformer.Canary
PackageVersion: 3.2.25093.1138
InstallerType: exe
Scope: machine
InstallModes:
- silent
- silentWithProgress
- interactive
InstallerSwitches:
  Silent: -install -silent
  SilentWithProgress: -install -silent
  Interactive: -install
  Upgrade: -update -silent
ProductCode: SystemInformer-Canary
ElevationRequirement: elevatesSelf
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/winsiderss/si-builds/releases/download/3.2.25093.1138/systeminformer-3.2.25093.1138-canary-setup.exe
  InstallerSha256: 221DE361845E9327E7783E45437B5E0B5FB190B4145EBF66C89E964E03DD0237
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-04-03
