# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: WinsiderSS.SystemInformer.Canary
PackageVersion: 3.1.24322.0
InstallerType: exe
Scope: machine
InstallModes:
- silent
- silentWithProgress
- interactive
InstallerSwitches:
  Silent: -install -silent
  SilentWithProgress: -install -silent
  Interactive: -install
  Upgrade: -update -silent
ProductCode: SystemInformer-Canary
ElevationRequirement: elevatesSelf
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/winsiderss/si-builds/releases/download/3.1.24322/systeminformer-3.1.24322-canary-setup.exe
  InstallerSha256: 905E484AD8B4FED391658D2B7191DC1C4D524260703565BD5BAEAF966C98ACB1
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2024-11-17
