# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: WinsiderSS.SystemInformer.Canary
PackageVersion: 3.2.25152.1910
InstallerType: exe
Scope: machine
InstallModes:
- silent
- silentWithProgress
- interactive
InstallerSwitches:
  Silent: -install -silent
  SilentWithProgress: -install -silent
  Interactive: -install
  Upgrade: -update -silent
ProductCode: SystemInformer-Canary
ElevationRequirement: elevatesSelf
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/winsiderss/si-builds/releases/download/3.2.25152.1910/systeminformer-3.2.25152.1910-canary-setup.exe
  InstallerSha256: 9733E77761811EC81E5D3747D3A9DFBBAAE02889FEE6F707E70FFBFD57150ECE
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-06-01
