name: Publish canary to winget

on:
    workflow_dispatch:
    release:
      types: [published]

permissions:
    contents: read

jobs:
    winget:
        name: Publish winget package
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v7
          with:
            token: ${{ secrets.PUSH_TOKEN }}
            ref: main
        - name: Publish winget manifest
          env:
            WINGET_CREATE_GITHUB_TOKEN: ${{ secrets.WINGET_CREATE_GITHUB_TOKEN }}
          run: .\winget\Publish.ps1 -Channel Canary -Version Latest -Output .\winget\ -Submit
        - name: Update winget manifest
          run: |
            git config user.name "Johnny Shaw"
            git config user.email johnny@jxy.dev
            git add .
            git commit -m "update winget manifest"
            git push
