name: Update winget canary manifest

on:
    workflow_dispatch:
    release:
      types: [published]

jobs:
    winget:
        name: Publish winget package
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v4
          with:
            token: ${{ secrets.PUSH_TOKEN }}
            ref: main
        - name: Publish winget manifest
          run: .\winget\Publish.ps1 -Channel Canary -Version Latest -Output .\winget\
        - name: Update winget manifest
          run: |
            git config user.name "Johnny Shaw"
            git config user.email johnny.shaw@live.com
            git add .
            git commit -m "update winget manifest"
            git push
